export const JOURNEY_STATUS = ['STARTED', 'CANCELLED', 'HOLD', 'ARCHIVED','ENDED','RESCHEDULED','NOT_STARTED','VERY_SOON']
export const DEFAULT_JOURNEY_STATUS = 'NOT_STARTED'
export const MODE_OF_TRANSPORT = ['BUS','RAIL','PLANE','SHIP','BIKE','CAR','OTHER']
