export const PAYMENT_STATUS = ['OPEN','COMPLETED','PENDING','FAILED']
export const DEFAULT_PAYMENT_STATUS = 'OPEN'
export const ORDER_STATUS = ['PENDING','CONFIRMED','DELIVERED','CANCELLED']
export const DEFAULT_ORDER_STATUS = 'PENDING'
